# Generated by Django 4.2.2 on 2023-09-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artentry',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
